# Generated by Django 3.2.22 on 2023-10-12 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EtiquetaAsociada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='AsignaciónTarea',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_finalizacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo_electronico',
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comentario',
            name='tarea',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.tarea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creador', to='gestiontareas.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tareas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.tarea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creador2', to='gestiontareas.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo_electrónico',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='hora_vencimiento',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipoestado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'Progreso'), ('COM', 'Completada')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='proyectoasignado',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.proyecto'),
        ),
        migrations.AddField(
            model_name='proyectoasignado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.usuario'),
        ),
        migrations.AddField(
            model_name='etiquetaasociada',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.etiqueta'),
        ),
        migrations.AddField(
            model_name='etiquetaasociada',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.tarea'),
        ),
        migrations.AddField(
            model_name='asignaciontarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.tarea'),
        ),
        migrations.AddField(
            model_name='asignaciontarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.usuario'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='tareas',
            field=models.ManyToManyField(through='gestiontareas.EtiquetaAsociada', to='gestiontareas.Tarea'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuarios',
            field=models.ManyToManyField(related_name='usuarios', through='gestiontareas.ProyectoAsignado', to='gestiontareas.Usuario'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuario',
            field=models.ManyToManyField(related_name='usuario2', through='gestiontareas.AsignacionTarea', to='gestiontareas.Usuario'),
        ),
    ]
