# Generated by Django 3.2.22 on 2023-10-12 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontareas', '0002_auto_20231012_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.usuario'),
        ),
    ]
